name: "Benchmark"

on:
  push:
    branches:
      - "develop"
  pull_request:

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15
        python-version:
          - "2.7"

    steps:

      - name: Check out zfec sources
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Identify compiler
        run: |
          gcc --version
          gcc -E -v - </dev/null 2>&1 | grep cc1

      - name: "Run benchmark"
        run: |
          pip install pyutil
          pip --verbose install .
          python bench/bench_zfec.py –k=223 –m=255
