# Build sdist+wheel packages using GitHub Actions.  Mostly adopted
# from https://cibuildwheel.readthedocs.io/en/stable/setup/

name: "Packages"

on:
  push:
    branches:
      # Do build on pushes to master.
      - "master"

    tags:
      # Do build on pushes to any release tag See
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      # for documentation about how patterns are matched.
      - "zfec-*"

  # Do build on pushes to any branch with an open pull request.
  pull_request:

  # Do build on different release events
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  release:
    types: [published, created, edited]

env:
  # Just make sure that Python can use zfec package
  CIBW_TEST_COMMAND: python -c "import zfec; print(zfec.__version__)"

jobs:
  build_wheels:
    name: "${{ matrix.wheel-selector }} wheel on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-18.04"
          - "windows-latest"
          - "macos-11"
        wheel-selector:
          - "cp37-*"
          - "cp38-*"
          - "cp39-*"
          - "cp310-*"
          - "pp37-*"
          - "pp38-*"

    steps:
      - name: Check out zfec sources
        uses: actions/checkout@v2
        with:
          # Check out the full history, including tags.  This is necessary to
          # construct non-release version numbers.
          fetch-depth: 0

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python3 -m pip install cibuildwheel==2.3.1
          python -m cibuildwheel --print-build-identifiers

      - name: "Run cibuildwheel"
        env:
          # Configure cibuildwheel to build just some of the total wheels we
          # could build for this architecture.  This yields better parallelism
          # on GitHub Actions execution.
          CIBW_BUILD: "${{ matrix.wheel-selector }}"

        run: |
          python3 -m cibuildwheel --output-dir wheelhouse

      - name: "Set CC=gcc on windows-latest"
        shell: bash
        if: runner.os == 'Windows'
        run: echo "CC=gcc" >> $GITHUB_ENV

      - name: "Build benchmark tool"
        run: |
          make -C bench bench_zfec STRIDE=4096
          bench/bench_zfec -h
          bench/bench_zfec -i 1 -r 1
          bench/bench_zfec -k 223 -m 255 -s 43488 -i 1 -r 1 -p "Bella ciao" -x
          bench/bench_zfec -k 223 -m 255 -s 43488 -i 1 -r 1 -p "Bella ciao" -x -A
        shell: bash

      - uses: actions/upload-artifact@v2
        name: Upload artifacts
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out zfec sources
        with:
          # Check out the full history, including tags.  This is necessary to
          # construct non-release version numbers.
          fetch-depth: 0

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Build sdist
        run: |
          python3 setup.py sdist

      - uses: actions/upload-artifact@v2
        name: Upload artifacts
        with:
          path: dist/*.tar.gz
