name: "QEMU tests"

on:
  push:
    branches:
      - 'main'
      - 'GH[1-9]+[0-9]*-*'
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:

      - name: Check out zfex sources
        uses: actions/checkout@v3

      - name: "Run unit tests on QEMU (cortex-a8)"
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: raspios_lite:latest
          cpu: cortex-a8
          optimize_image: no
          commands: |
            sudo apt-get --yes update
            sudo apt-get --yes install python3-pip
            yes | pip install twisted pyutil
            yes | pip install --verbose .[test]
            trial zfex

      - name: "Run unit tests on QEMU (cortex-a8) with ZFEX_USE_ARM_NEON"
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: raspios_lite:latest
          cpu: cortex-a8
          optimize_image: no
          commands: |
            sudo apt-get --yes update
            sudo apt-get --yes install python3-pip
            yes | pip install twisted pyutil
            export CFLAGS="-DZFEX_USE_ARM_NEON -mcpu=cortex-a8 -mfpu=neon -O3" && yes | pip install --verbose .[test]
            trial zfex

      - name: "Build and run benchmark tool on QEMU (cortex-a8)"
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: raspios_lite:latest
          cpu: cortex-a8
          optimize_image: no
          commands: |
            ###################
            Green='\e[0;32m'
            Red='\e[0;31m'
            Yellow='\e[0;33m'
            Cyan='\e[0;36m'
            Normal='\e[0m' # No Color
            ###################
            LE="${Yellow}[LE]${Normal}"
            make -C bench bench_zfex ZFEX_STRIDE=4096 UNROLL=8
            echo "::group::${LE} Run default benchmark"
            bench/bench_zfex -i 1 -r 1
            echo "::endgroup::"
            echo "::group::${LE} Run custom benchmark and show checksums"
            bench/bench_zfex -k 223 -m 255 -s 43488 -i 1 -r 1 -p "Bella ciao" -x
            echo "::endgroup::"
            make -C bench clean
            CFLAGS="-DZFEX_USE_ARM_NEON -mcpu=cortex-a8 -mfpu=neon -O3 -static" make -C bench bench_zfex
            echo "::group::${LE} Run default NEON benchmark"
            bench/bench_zfex -i 1 -r 1
            echo "::endgroup::"
            echo "::group::${LE} Run custom NEON benchmark and show checksums"
            bench/bench_zfex -k 223 -m 255 -s 43488 -i 1 -r 1 -p "Bella ciao" -x
            echo "::endgroup::"
            echo "::group::${LE} Run custom aligned NEON benchmark and show checksums"
            bench/bench_zfex -k 223 -m 255 -s 43488 -i 1 -r 1 -p "Bella ciao" -x -A
            echo "::endgroup::"
            make -C bench clean
            ###################
