name: "Tests | Intel"

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - ubuntu-latest
          - windows-latest
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "pypy-3.7"
          - "pypy-3.8"
        include:
          - os: "ubuntu-latest"
            python-version: "3.6"

    steps:

      - name: Check out zfex sources
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Run python API unit tests"
        run: |
          pip install .[test]
          trial zfex
